### PR TITLE
Change `--from-dir` init flow

### LINKED ISSUE #916: Make tests more robust with environment variable checks
## Background

Environment variables `DAPR_RUNTIME_VERSION` and `DAPR_DASHBOARD_VERSION` are used by e2e tests.

https://github.com/dapr/cli/blob/68c2ab84d48892a0deb42e8cb4c3b1fbc356927c/tests/e2e/kubernetes/kubernetes_test.go#L26-L29

https://github.com/dapr/cli/blob/050eb553f2304aca08cdcbae86f44a97552fa121/tests/e2e/standalone/standalone_test.go#L43-L47

Locally, when someone runs `make test-e2e-sh` without these environment variables set, it fails with the following error:
image

This does not give any idea on what the actual problem is.

<details>
<summary>CLI logs | head :</summary>

```bash
dapr ➜ /go/src/github.com/dapr/cli (master) $ make test-e2e-sh
# The desire here is to download this test dependency without polluting go.mod
# In golang >=1.16 there is a new way to do this with `go install gotest.tools/gotestsum@latest`
# But this doesn't work with <=1.15, so we do it the old way for now 
# (see: https://golang.org/ref/mod#go-install)
GO111MODULE=off go get gotest.tools/gotestsum
gotestsum --jsonfile test_output.json --format standard-verbose -- -count=1 -tags=e2e ./tests/e2e/standalone/...
=== RUN   TestStandaloneInstall
=== RUN   TestStandaloneInstall/test_install
    standalone_test.go:190: {"time":"2022-03-07T12:36:21.3888015Z","status":"pending","msg":"Making the jump to hyperspace..."}
        {"time":"2022-03-07T12:36:21.3943455Z","status":"info","msg":"Installing runtime version "}
        {"time":"2022-03-07T12:36:22.1383481Z","status":"pending","msg":"Downloading binaries and setting up components..."}
        {"time":"2022-03-07T12:36:22.2067208Z","status":"failure","msg":"Downloading binaries and setting up components..."}
        {"time":"2022-03-07T12:36:22.2067746Z","status":"failure","msg":"docker: invalid reference format.\nSee 'docker run --help'.\n"}
        
    standalone_test.go:191: 
                Error Trace:    standalone_test.go:191
                Error:          Received unexpected error:
                                exit status 1
                Test:           TestStandaloneInstall/test_install
                Messages:       init failed
=== RUN   TestStandaloneInstall/test_install_from_custom_registry
    standalone_test.go:199: Custom image registry is not set, skipping the test for now..
=== RUN   TestStandaloneInstall/test_run
=== RUN   TestStandaloneInstall/test_run/Normal_exit,_socket:_
    standalone_test.go:386: ℹ️  Starting Dapr with id Hyenaberyl-Pixie. HTTP Port: 34507. gRPC Port: 44421
        ❌  fork/exec /home/dapr/.dapr/bin/daprd: no such file or directory
        
    standalone_test.go:387: 
                Error Trace:    standalone_test.go:387
                Error:          Received unexpected error:
                                exit status 1
                Test:           TestStandaloneInstall/test_run/Normal_exit,_socket:_
                Messages:       run failed
```
</details>

## Fix

Add checks for environment variables in the tests initialization and fail with a proper error message with they are missing.

### LINKED ISSUE #938: dapr init in airgap fails when default image registry is set to ghcr
## Expected Behavior

dapr init --from-dir <path-to-bundle-location> should load the binaries as well as images in bundle correctly always.

## Actual Behavior

In default case (when DAPR_DEFAULT_IMAGE_REGISTRY is set to "dockerhub"), it works fine. But if the user sets it to "ghcr" it fails.

## Steps to Reproduce the Problem

$ export DAPR_DEFAULT_IMAGE_REGISTRY="ghcr"
$ cd daprbundle
$ ./dapr init --from-dir .

It gives up following logs:
- - - 
  Making the jump to hyperspace...
⚠  Local bundle installation using from-dir flag is currently a preview feature.
ℹ️  Container images will be pulled from Dapr GitHub container registry
ℹ️  Installing runtime version latest
→  Extracting binaries and setting up components... 
Dapr runtime installed to /home/shivamkm07/.dapr/bin, you may run the following to add it to your path if you want to run daprd directly:
    export PATH=$PATH:/home/shivamkm07/.dapr/bin
❌  Extracting binaries and setting up components...
❌  fail to read docker image file ghcr.io/dapr/dapr:1.7.0-rc.2: open docker/ghcr.io-dapr-dapr-1.7.0-rc.2.tar.gz: no such file or directory
- - -
## Reason behind failure 

The reason it's failing is that the [installer-bundle](https://github.com/dapr/installer-bundle/releases) pulls image from dockerhub and  saves it with filename as `daprio-dapr-1.7.0-rc.2.tar.gz`(for runtime_ver=1.7.0-rc.2).
In CLI, when the default registry is `"dockerhub"`, image is set to: `daprio/dapr:1.7.0-rc.2` and it searches for filename `daprio-dapr-1.7.0-rc.2.tar.gz` and it works fine. But when the default registry is set to `"ghcr"`, it searches for filename `ghcr.io-dapr-dapr-1.7.0-rc.2.tar.gz` which it can't find and so throws error.

## Possible Solutions

1. Don't have any change in installer-bundle workflow. In CLI, set image filename to be `daprio-dapr-<runtime_ver>.tar.gz` in case of airgap mode. This would require minimal change for now. But in future, when we decide to switch to `ghcr` in installer-bundle-workflow as well, this would require change in both CLI and workflow and would be a breaking change at that point(earlier versions of CLI wouldn't be compatible with new bundles).
2. In installer-bundle-workflow, pull from ghcr instead of dockerhub and in both CLI and workflow, set the filename to be `dapr-dapr-<runtime_ver>.tar.gz` in case of airgap mode irrespective of any environement variables. This would work fine, but again would be a breaking change in case we would switch to dockerhub from ghcr in workflow in future.
3. Don't keep the owner names at all in filenames. So for example the filename for dapr image would be just `dapr-<runtime_ver>.tar.gz`. This would be consistent in future if we switch from ghcr to dockerhub or vice versa in future.

## Release Note

RELEASE NOTE: **FIX** Bug in CLI airgap installation

RELEASE NOTE:

### PR DESCRIPTION
**Pull request by mukundansundar**
# Description

Fix `--from-dir` init flow. 

Based on the PR https://github.com/dapr/installer-bundle/pull/3, this PR changes init flow when `--from-dir` flag is specified to expect a `details.json` file.
It will parse the `details.json` file to know the image that was saved as well as the file name it was saved as. 
Also as previous flow, the runtime and dashboard versions are determined from the `details.json` file as well.

isAirGapInit just encapsulates the value of bool comparing fromDir length to zero. isAirGapInit seems a more expressive way of checking for a particular condition in a flow.

Added more comments on the current init flow. 

Create a separate `bundle.go` which basically just parses the `details.json` file and added a unit test for the same. 

When both `--from-dir` and `--image-registry` is given, changed `cmd/init.go` flow to error out that both flags are given. 

Fixed the e2e tests to error out gracefully if required env vars are not set.

Output of local tests run 
```bash
$  export DAPR_DEFAULT_IMAGE_REGISTRY=GHCR                                                 

$ ./release/dapr init --from-dir ../bundle/daprbundle
⌛  Making the jump to hyperspace...
⚠  Local bundle installation using from-dir flag is currently a preview feature.
ℹ️  Installing runtime version 1.7.0-rc.2
↓  Extracting binaries and setting up components... 
Dapr runtime installed to /Users/test/.dapr/bin, you may run the following to add it to your path if you want to run daprd directly:
    export PATH=$PATH:/Users/test/.dapr/bin
↙  Extracting binaries and setting up components... Loaded image: daprio/dapr:1.7.0-rc.2
✅  Extracting binaries and setting up components...
✅  Extracted binaries and completed components set up.
ℹ️  daprd binary has been installed to /Users/test/.dapr/bin.
ℹ️  dapr_placement container is running.
ℹ️  Use `docker ps` to check running containers.
✅  Success! Dapr is up and running. To get started, go here: https://aka.ms/dapr-getting-started

$ docker ps 
CONTAINER ID   IMAGE                    COMMAND         CREATED              STATUS              PORTS                      NAMES
fbfbd3403092   daprio/dapr:1.7.0-rc.2   "./placement"   About a minute ago   Up About a minute   0.0.0.0:50005->50005/tcp   dapr_placement

$ ./release/dapr uninstall --all                     
ℹ️  Removing Dapr from your machine...
ℹ️  Removing directory: /Users/test/.dapr/bin
ℹ️  Removing container: dapr_placement
⚠  WARNING: dapr_redis container does not exist
⚠  WARNING: dapr_zipkin container does not exist
ℹ️  Removing directory: /Users/test/.dapr
✅  Dapr has been removed successfully

$ ./release/dapr init —runtime-version 1.7.0-rc.2
⌛  Making the jump to hyperspace...
ℹ️  Container images will be pulled from Dapr GitHub container registry
ℹ️  Installing runtime version 1.7.0-rc.2
↗  Downloading binaries and setting up components... 
Dapr runtime installed to /Users/test/.dapr/bin, you may run the following to add it to your path if you want to run daprd directly:
    export PATH=$PATH:/Users/test/.dapr/bin
✅  Downloading binaries and setting up components...
✅  Downloaded binaries and completed components set up.
ℹ️  daprd binary has been installed to /Users/test/.dapr/bin.
ℹ️  dapr_placement container is running.
ℹ️  dapr_redis container is running.
ℹ️  dapr_zipkin container is running.
ℹ️  Use `docker ps` to check running containers.
✅  Success! Dapr is up and running. To get started, go here: https://aka.ms/dapr-getting-started

$ docker ps 
CONTAINER ID   IMAGE                          COMMAND                  CREATED          STATUS                    PORTS                              NAMES
4ad6ed31c863   ghcr.io/dapr/dapr:1.7.0-rc.2   "./placement"            20 seconds ago   Up 19 seconds             0.0.0.0:50005->50005/tcp           dapr_placement
789f50de37ec   ghcr.io/dapr/3rdparty/zipkin   "start-zipkin"           21 seconds ago   Up 20 seconds (healthy)   9410/tcp, 0.0.0.0:9411->9411/tcp   dapr_zipkin
f6d54c1e00b5   ghcr.io/dapr/3rdparty/redis    "docker-entrypoint.s…"   21 seconds ago   Up 20 seconds             0.0.0.0:6379->6379/tcp             dapr_redis

$ ./release/dapr init           
⌛  Making the jump to hyperspace...
ℹ️  Container images will be pulled from Dapr GitHub container registry
ℹ️  Installing runtime version 1.6.1
↙  Downloading binaries and setting up components... ℹ️  Placement image not found in Github container registry, pulling it from Docker Hub
↑  Downloading binaries and setting up components... 
Dapr runtime installed to /Users/test/.dapr/bin, you may run the following to add it to your path if you want to run daprd directly:
    export PATH=$PATH:/Users/test/.dapr/bin
✅  Downloading binaries and setting up components...
✅  Downloaded binaries and completed components set up.
ℹ️  daprd binary has been installed to /Users/test/.dapr/bin.
ℹ️  dapr_placement container is running.
ℹ️  dapr_redis container is running.
ℹ️  dapr_zipkin container is running.
ℹ️  Use `docker ps` to check running containers.
✅  Success! Dapr is up and running. To get started, go here: https://aka.ms/dapr-getting-started

$ docker ps
CONTAINER ID   IMAGE                          COMMAND                  CREATED          STATUS                    PORTS                              NAMES
8cf807b85281   daprio/dapr:1.6.1              "./placement"            44 seconds ago   Up 43 seconds             0.0.0.0:50005->50005/tcp           dapr_placement
79761ca1a39c   ghcr.io/dapr/3rdparty/redis    "docker-entrypoint.s…"   45 seconds ago   Up 45 seconds             0.0.0.0:6379->6379/tcp             dapr_redis
4b78af8d1428   ghcr.io/dapr/3rdparty/zipkin   "start-zipkin"           45 seconds ago   Up 45 seconds (healthy)   9410/tcp, 0.0.0.0:9411->9411/tcp   dapr_zipkin

$ ./release/dapr uninstall --all 
....
....
$ export DAPR_DEFAULT_IMAGE_REGISTRY=localhost:5000
$ ./release/dapr init --runtime-version 1.7.0-rc.2
⌛  Making the jump to hyperspace...
❌  environment variable "DAPR_DEFAULT_IMAGE_REGISTRY" can only be set to GHCR
```

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

closes #938 
closes #916 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

File: cmd/init.go [hunk 1]
```diff
@@ -103,10 +105,15 @@ dapr init --from-dir <path-to-directory>
 				dockerNetwork = viper.GetString("network")
 				imageRegistryURL = viper.GetString("image-registry")
 			}
-			if fromDir != "" {
+			// If both --image-registry and --from-dir flags are given, error out saying only one can be given.
+			if len(strings.TrimSpace(imageRegistryURL)) != 0 && len(strings.TrimSpace(fromDir)) != 0 {
```
Comment (shubham1172) [inline cmd/init.go:109]: Is `TrimSpace` needed here? It's directly coming from the viper/pflag.

File: cmd/init.go [hunk 2]
```diff
@@ -103,10 +105,15 @@ dapr init --from-dir <path-to-directory>
...
+				print.FailureStatusEvent(os.Stderr, "both --image-registry and --from-dir flags cannot be given at the same time")
+				os.Exit(1)
+			}
+			if len(strings.TrimSpace(fromDir)) != 0 {
 				print.WarningStatusEvent(os.Stdout, "Local bundle installation using from-dir flag is currently a preview feature.")
```
Comment (shubham1172) [inline cmd/init.go:114]: Should we add that it's only available from XYZ version like `--image-registry`?

File: tests/e2e/common/common.go [hunk 3]
```diff
@@ -70,6 +70,22 @@ type TestCase struct {
 	Callable func(*testing.T)
 }
 
+// GetFromEnvVar will return values from required environment variables,
+// if not environemt variables are not set it fails the test.
```
Comment (shubham1172) [inline tests/e2e/common/common.go:74]: nit: typo

Comment (shubham1172) [inline tests/e2e/common/common.go:74]:
```suggestion
// if environment variables are not set, it fails the test.
```

File: tests/e2e/common/common.go [hunk 4]
```diff
@@ -70,6 +70,22 @@ type TestCase struct {
...
+func GetFromEnvVar(t *testing.T) (daprRuntimeVersion string, daprDashboardVersion string) {
```
Comment (shubham1172) [inline tests/e2e/common/common.go:75]: func name => `MustEnvVar`?

File: cmd/init.go (hunk 1 above)
Comment (mukundansundar) [reply cmd/init.go:109]:
```bash
$ ./release/dapr init --from-dir "   " --image-registry localhost:5000  
⌛  Making the jump to hyperspace...
⚠  Flag --image-registry is a preview feature and is subject to change. It is only available from CLI version 1.7 onwards.
❌  could not connect to Docker. Docker may not be installed or running
```

I had local docker turned off... but if "   " is given within quotes, viper/pflag still allows it through as a value ...
But in this case if `TrimSpace` is not there 
```bash
./release/dapr init --from-dir "   " --image-registry localhost:5000 
⌛  Making the jump to hyperspace...
❌  both --image-registry and --from-dir flags cannot be given at the same time
```
This should not be the case since `--from-dir` is empty and has no valid value.

File: pkg/standalone/bundle.go [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+
+package standalone
+
+import (
+	"encoding/json"
+	"fmt"
+	"io/ioutil"
+)
+
+const bundleDetailsFileName = "details.json"
```
Comment (surenderssm) [inline pkg/standalone/bundle.go:22]: Is this file as part of spec/understanding between cli and bundle installer? Or there is a probability of the name change?

Comment (mukundansundar) [reply pkg/standalone/bundle.go:22]: part of the spec/understanding ... see this change ... https://github.com/dapr/installer-bundle/pull/3

File: cmd/init.go (hunk 1 above)
Comment (shubham1172) [reply cmd/init.go:109]: Hmm, if user is giving an invalid value (they are intentional about with since they are using quotes), shouldn't it error out?

File: pkg/standalone/bundle.go [hunk 6]
```diff
@@ -0,0 +1,56 @@
...
+	bytes, err := ioutil.ReadFile(detailsFilePath)
+	if err != nil {
+		return err
+	}
+
+	err = json.Unmarshal(bytes, &b)
+	if err != nil {
+		return err
+	}
+	if b.RuntimeVersion == nil || b.DashboardVersion == nil || b.DaprImageName == nil || b.DaprImageFileName == nil {
```
Comment (surenderssm) [inline pkg/standalone/bundle.go:44]: How does this behave if daprd is present in json but with empty value?

File: pkg/standalone/standalone.go [hunk 7]
```diff
@@ -141,47 +148,62 @@ func isBinaryInstallationRequired(binaryFilePrefix, installDir string) (bool, er
...
 	if !slimMode {
+		// If --slim installation is not requested, check if docker is installed.
 		dockerInstalled := utils.IsDockerInstalled()
 		if !dockerInstalled {
 			return errors.New("could not connect to Docker. Docker may not be installed or running")
 		}
 
-		// Initialize default registry only if it is not airgap mode or from private registries.
-		if len(strings.TrimSpace(imageRegistryURL)) == 0 && len(strings.TrimSpace(fromDir)) == 0 {
+		// Initialize default registry only if --slim or --image-registry or --from-dir are not given.
```
Comment (DeepanshuA) [inline pkg/standalone/standalone.go:159]:
```suggestion
		// Initialize default registry only if any of --slim or --image-registry or --from-dir are not given.
```

File: pkg/standalone/bundle_test.go [hunk 8]
```diff
@@ -0,0 +1,80 @@
...
+	correctDetails := `{
+		"daprd" : "1.7.0-rc.2",
+		"dashboard": "0.10.0-rc.2",
+		"cli": "1.7.0-rc.2",
+		"daprBinarySubDir": "dist",
+		"dockerImageSubDir": "docker",
+		"daprImageName": "daprio/dapr:1.7.2-rc.2",
+		"daprImageFileName": "daprio-dapr-1.7.2-rc.2.tar.gz"
+	}`
+	f, err := os.CreateTemp("", "*-details.json")
```
Comment (surenderssm) [inline pkg/standalone/bundle_test.go:33]: Just curious why instead of creating this on the fly, we not keeping as a file in folder

File: pkg/standalone/bundle.go (hunk 6 above)
Comment (mukundansundar) [reply pkg/standalone/bundle.go:44]: good catch ... fixing the check ...

File: pkg/standalone/standalone.go [hunk 9]
```diff
@@ -448,10 +451,27 @@ func runPlacementService(wg *sync.WaitGroup, errorChan chan<- error, info initIn
...
+		ghcrImageName:      daprGhcrImageName,
+		dockerHubImageName: daprDockerImageName,
+		imageRegistryURL:   info.imageRegistryURL,
+		imageRegistryName:  defaultImageRegistryName,
+	}
 
-	if info.fromDir != "" {
-		dir := path_filepath.Join(info.fromDir, dockerImageSubDir)
-		err = loadDocker(dir, image)
+	if isAirGapInit(info.fromDir) {
```
Comment (DeepanshuA) [inline pkg/standalone/standalone.go:463]: As this check is getting used at various places in standalone.go, should we just set a boolean flag once and use it everywhere, instead of checking every time if fromDir's length is 0 after trimming space.

File: pkg/standalone/bundle_test.go (hunk 8 above)
Comment (mukundansundar) [reply pkg/standalone/bundle_test.go:33]: because we are using ioutil.ReadFile(filename) which actually reads a given file location. That is what is done by the parseDetails function ... It reads a file and parses details from the file ... 
probably renaming the function to `readAndParseDetails` would be better?

File: pkg/standalone/docker.go [hunk 10]
```diff
@@ -121,14 +121,7 @@ func parseDockerError(component string, err error) error {
...
 
-func imageFileName(image string) string {
-	filename := image + ".tar.gz"
-	filename = strings.ReplaceAll(filename, "/", "-")
-	filename = strings.ReplaceAll(filename, ":", "-")
-	return filename
-}
-
-func TryPullImage(imageName string) bool {
+func tryPullImage(imageName string) bool {
```
Comment (surenderssm) [inline pkg/standalone/docker.go:124]: Is this scope change intentional?

Comment (mukundansundar) [reply pkg/standalone/docker.go:124]: yes ... why export it ?

File: pkg/standalone/standalone.go (hunk 9 above)
Comment (surenderssm) [reply pkg/standalone/standalone.go:463]: +1

File: pkg/standalone/standalone.go [hunk 11]
```diff
@@ -554,34 +574,36 @@ func installPlacement(wg *sync.WaitGroup, errorChan chan<- error, info initInfo)
...
 	}
 
 	extractedFilePath, err := extractFile(filepath, dir, binaryFilePrefix)
 	if err != nil {
 		return err
 	}
 
-	if fromDir == "" {
+	// remove downloaded archive from the default dapr bin path.
+	if !isAirGapInit(info.fromDir) {
```
Comment (surenderssm) [inline pkg/standalone/standalone.go:606]: can this be moved to defer, so it doesn't slow down the init

File: pkg/standalone/standalone.go [hunk 12]
```diff
@@ -554,34 +574,36 @@ func installPlacement(wg *sync.WaitGroup, errorChan chan<- error, info initInfo)
...
 		err = os.Remove(filepath)
 		if err != nil {
```
Comment (surenderssm) [inline pkg/standalone/standalone.go:608]: shouldn't we continue even if removing fails, the best attempt approach might add value here, thoughts?

Comment (mukundansundar) [reply pkg/standalone/standalone.go:608]: good point @surenderssm ... Can that be a separate issue ? I do not want to increase the scope of this PR.

Comment (surenderssm) [reply pkg/standalone/standalone.go:608]: Agree, filed a issue : #946

File: pkg/standalone/standalone.go (hunk 11 above)
Comment (mukundansundar) [reply pkg/standalone/standalone.go:606]: please create a separate issue for this change along with the comment below.

File: cmd/init.go (hunk 1 above)
Comment (mukundansundar) [reply cmd/init.go:109]: IMO no it should not.

File: pkg/standalone/standalone.go (hunk 11 above)
Comment (surenderssm) [reply pkg/standalone/standalone.go:606]: taken care

File: cmd/init.go (hunk 1 above)
Comment (surenderssm) [reply cmd/init.go:109]: current approach looks good to me.

File: pkg/standalone/bundle.go [hunk 13]
```diff
@@ -0,0 +1,63 @@
...
+		return err
+	}
+	if isStringNilOrEmpty(b.RuntimeVersion) || isStringNilOrEmpty(b.DashboardVersion) ||
+		isStringNilOrEmpty(b.DaprImageName) || isStringNilOrEmpty(b.DaprImageFileName) {
+		return fmt.Errorf("required fields are missing in %s", detailsFilePath)
+	}
+	return nil
+}
+
+func isStringNilOrEmpty(val *string) bool {
```
Comment (surenderssm) [inline pkg/standalone/bundle.go:53]: Beautiful, sorted for one and all 💯

File: pkg/standalone/bundle.go [hunk 14]
```diff
@@ -0,0 +1,63 @@
...
+	DashboardVersion  *string `json:"dashboard"`
+	CLIVersion        *string `json:"cli"`
+	BinarySubDir      *string `json:"daprBinarySubDir"`
+	ImageSubDir       *string `json:"dockerImageSubDir"`
+	DaprImageName     *string `json:"daprImageName"`
+	DaprImageFileName *string `json:"daprImageFileName"`
+}
+
+// readAndParseDetails reads the file in detailsFilePath and tries to parse it into the bundleDetails struct.
+func (b *bundleDetails) readAndparseDetails(detailsFilePath string) error {
```
Comment (DeepanshuA) [inline pkg/standalone/bundle.go:36]:
```suggestion
func (b *bundleDetails) readAndParseDetails(detailsFilePath string) error {
```

File: pkg/standalone/bundle.go [hunk 15]
```diff
@@ -0,0 +1,63 @@
...
+	}
+
+	err = json.Unmarshal(bytes, &b)
+	if err != nil {
+		return err
+	}
+	if isStringNilOrEmpty(b.RuntimeVersion) || isStringNilOrEmpty(b.DashboardVersion) ||
+		isStringNilOrEmpty(b.DaprImageName) || isStringNilOrEmpty(b.DaprImageFileName) {
+		return fmt.Errorf("required fields are missing in %s", detailsFilePath)
+	}
```
Comment (shivamkm07) [inline pkg/standalone/bundle.go:49]: Why are `BinarySubDir` and `ImageSubDir` not required fields? Shouldn't we pick the Dirs provided in `details.json`?

File: pkg/standalone/standalone.go [hunk 16]
```diff
@@ -448,10 +455,27 @@ func runPlacementService(wg *sync.WaitGroup, errorChan chan<- error, info initIn
...
+		imageRegistryURL:   info.imageRegistryURL,
+		imageRegistryName:  defaultImageRegistryName,
+	}
 
-	if info.fromDir != "" {
-		dir := path_filepath.Join(info.fromDir, dockerImageSubDir)
-		err = loadDocker(dir, image)
+	if isAirGapInit {
+		// if --from-dir flag is given load the image details from the installer-bundle.
+		dir := path_filepath.Join(info.fromDir, daprImageSubDir)
```
Comment (shivamkm07) [inline pkg/standalone/standalone.go:469]:
```suggestion
		`dir := path_filepath.Join(info.fromDir, info.bundleDet.ImageSubDir)`
```

File: pkg/standalone/standalone.go [hunk 17]
```diff
@@ -554,34 +578,36 @@ func installPlacement(wg *sync.WaitGroup, errorChan chan<- error, info initInfo)
...
+func installBinary(version, binaryFilePrefix, githubRepo string, info initInfo) error {
 	var (
 		err      error
 		filepath string
 	)
 
 	dir := defaultDaprBinPath()
-	if fromDir == "" {
+	if isAirGapInit {
+		filepath = path_filepath.Join(info.fromDir, daprBinarySubDir, binaryName(binaryFilePrefix))
```
Comment (shivamkm07) [inline pkg/standalone/standalone.go:596]:
```suggestion
		filepath = path_filepath.Join(info.fromDir, info.bundleDet.BinarySubDir, binaryName(binaryFilePrefix))
```

File: pkg/standalone/standalone.go [hunk 18]
```diff
@@ -1084,7 +1115,7 @@ func checkFallbackImgForPlacement(imageInfo daprImageInfo, fromDir string) bool
 func resolveImageURI(imageInfo daprImageInfo) (string, error) {
 	if imageInfo.imageRegistryURL != "" {
```
Comment (shivamkm07) [inline pkg/standalone/standalone.go:1116]:
```suggestion
	if len(strings.TrimSpace(imageRegistryURL)) != 0 {
```

If we are using TrimSpace everywhere, it should be here as well.

File: pkg/standalone/standalone.go [hunk 19]
```diff
@@ -223,6 +249,7 @@ func Init(runtimeVersion, dashboardVersion string, dockerNetwork string, slimMod
 	}
 
 	info := initInfo{
+		bundleDet:        &bundleDet, // will be nil if fromDir is empty, so must be used in conjunction with fromDir.
```
Comment (shivamkm07) [inline pkg/standalone/standalone.go:252]:
```suggestion
		bundleDet:        &bundleDet, // must be used in conjunction with fromDir.
```

&bundleNet won't be nil even if --from-dir flag is not there

Comment (mukundansundar) [reply pkg/standalone/standalone.go:252]: addressed comment.

**Review by shubham1172 — APPROVED** [review]

File: tests/e2e/common/common.go [hunk 20]
```diff
@@ -70,6 +70,22 @@ type TestCase struct {
 	Callable func(*testing.T)
 }
 
+// GetFromEnvVar will return values from required environment variables,
+// if environment variables are not set it fails the test.
+func GetFromEnvVar(t *testing.T) (daprRuntimeVersion string, daprDashboardVersion string) {
```
Comment (shubham1172) [inline tests/e2e/common/common.go:75]: nit: clarify intent
```suggestion
func GetVersionsFromEnvVar(t *testing.T) (daprRuntimeVersion string, daprDashboardVersion string) {
```

File: pkg/standalone/bundle.go (hunk 5 above)
Comment (shubham1172) [reply pkg/standalone/bundle.go:23]: Once that PR is merged, do you want to add link to that as comment? Will be helpful for code-viewers to get the context.

**Comment by mukundansundar** [comment]
@yaron2 @artursouza I have retriggered the Darwin automated workflow ... if it fails or is still running later, it seems to be an issue with the install docker action that we use ... not related to this PR ... there have been previous runs that did pass as is for the PR and it does pass in linux.

**Review by artursouza — APPROVED** [review]
