### PR TITLE
Pin bitnami chart version for redis

### LINKED ISSUE #1436: dapr init -k --dev is in crash loop on redis init, failing redis component load
## Actual 
This quickstart repro's the issue.  
image

This appears to only happen in the GH action runner, and not on my local kind installations.
https://github.com/dapr/quickstarts/actions/runs/9702023201/job/26776912327#step:18:82

## Expected
It should look like this fully passing
image

## Release Note

RELEASE NOTE:

### PR DESCRIPTION
**Pull request by yaron2**
Pins the bitnami version to a stable one and removes unneeded Redis replicas for dev mode.

Fixes #1436 
and https://github.com/dapr/quickstarts/issues/1048

### CODE REVIEW

File: pkg/kubernetes/kubernetes.go [hunk 1]
```diff
@@ -40,6 +40,7 @@ const (
 	daprReleaseName      = "dapr"
 	dashboardReleaseName = "dapr-dashboard"
 	latestVersion        = "latest"
+	bitnamiStableVersion = "17.14.5"
```
Comment (paulyuk) [inline pkg/kubernetes/kubernetes.go:43]: Verified version

**Review by paulyuk — APPROVED** [review]
We'll just want to verify that the statestore CRD's creds from --dev work with this.

**Comment by paulyuk** [comment]
> We'll just want to verify that the `statestore` CRD's creds from `dapr init -k --dev` work with this.

Actually i recommend CLI no longer applies statestore anymore.  This leads to too many troubleshooting conflicts.  The main value here is installing redis. not applying the statestore.

**Comment by marcduiker** [comment]
@holopin-bot @yaron2 Thanks Yaron!
