### PR TITLE
Fix for Quote in username errors dapr init #972

### LINKED ISSUE #972: Quote in username errors dapr init
## In what area(s)?

Dapr cli; in particular dapr init

## What version of Dapr?

dapr --version
CLI version: 1.7.0
Runtime version: 1.7.2

## Expected Behavior

Dapr init runs smoothly.

## Actual Behavior

Dapr init errors out because it doesn't use proper escaping of the userprofile env var path.

```
dapr init
Making the jump to hyperspace...
Container images will be pulled from Docker Hub
Installing runtime version 1.7.2
Downloading binaries and setting up components...
error moving dashboard binary to path: At line:1 char:133
+ ... ]::GetEnvironmentVariable('Path','user') + ';C:\Users\Carlin'tVeld\.d ...
+                                                                  ~
Missing ')' in method call.
At line:1 char:156
+ ... Variable('Path','user') + ';C:\Users\Carlin'tVeld\.dapr\bin', 'user')
+                                                                        ~~
The string is missing the terminator: '.
At line:1 char:133
+ ... Variable('Path','user') + ';C:\Users\Carlin'tVeld\.dapr\bin', 'user')
+                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'tVeld\.dapr\bin', 'user')' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingEndParenthesisInMethodCall
```

## Steps to Reproduce the Problem

I believe just set the userprofile env var to something with a quote (apostrophe) and run dapr init.

## Release Note

RELEASE NOTE: **FIX** DAPR CLI now works with user profile names with quotes inside.

### PR DESCRIPTION
**Pull request by mohitpalsingh**
# Description

dapr init fails to run with certain username on Windows.
This issue was caused because of an extra apostrophe or single quote in the username since powershell considers it as special character and hence creates syntax issues. To solve this, I created a function in '/utils/utils.go' to take any command and converts into powershell compatible command by appending another quote character after every such character. This makes the command powershell compatible. Now it doesn't throw any syntax error and runs as expected.

Closes #972 

# Testing

PS C:\Users\Carlin'tVeld> cd D:
PS D:\> .\dapr.exe init
Making the jump to hyperspace...
Container images will be pulled from Docker Hub
Installing runtime version 1.11.1
Downloading binaries and setting up components...
Downloaded binaries and completed components set up.
daprd binary has been installed to C:\Users\Carlin'tVeld\.dapr\bin.
dapr_placement container is running.
dapr_redis container is running.
dapr_zipkin container is running.
Use `docker ps` to check running containers.
Success! Dapr is up and running. To get started, go here: https://aka.ms/dapr-getting-started
PS D:\>

### CODE REVIEW

**Review by mukundansundar — COMMENTED** [review]
@mohitpalsingh thanks for the contribution. 
Can you add unit tests for this?

File: utils/utils.go [hunk 1]
```diff
@@ -403,3 +403,18 @@ func FindFileInDir(dirPath, fileName string) (string, error) {
 	}
 	return filePath, nil
 }
+
+// FixCommandWithApostrophe corrects the passed command which might have apostrophes in it.
+func FixCommandWithApostrophe(destDir *string) {
```
Comment (shubham1172) [inline utils/utils.go:408]: Will `strings.Replace(destDir, "'", "''", -1)` not work?

Comment (mohitpalsingh) [reply utils/utils.go:408]: addressed

File: utils/utils.go [hunk 2]
```diff
@@ -404,17 +404,7 @@ func FindFileInDir(dirPath, fileName string) (string, error) {
...
-	for i := 0; i < len(bytes); i++ {
-		result = append(result, bytes[i])
-		if bytes[i] == '\'' {
-			result = append(result, '\'')
-		}
-	}
-
-	*destDir = string(result)
+// SanitizeDir corrects any syntactical errors in the passed directory.
+func SanitizeDir(destDir *string) {
```
Comment (shubham1172) [inline utils/utils.go:408]: Avoid in-place pointer updates.
```suggestion
func SanitizeDir(destDir string) string {
```

Comment (mohitpalsingh) [reply utils/utils.go:408]: addressed

**Review by shubham1172 — CHANGES_REQUESTED** [review]
Thanks @mohitpalsingh for your first contribution, can you just fix the lint failure, overall PR LGTM.

**Comment by mohitpalsingh** [comment]
> Thanks @mohitpalsingh for your first contribution, can you just fix the lint failure, overall PR LGTM.

Thank you for the feedback and acknowledging my contribution. I appreciate your support. I have addressed the lint failure and made the necessary fixes. Your approval of the overall pull request means a lot to me. Thank you once again for your time and guidance.

File: utils/utils.go [hunk 3]
```diff
@@ -403,3 +403,8 @@ func FindFileInDir(dirPath, fileName string) (string, error) {
 	}
 	return filePath, nil
 }
+
+// SanitizeDir corrects any syntactical errors in the passed directory.
```
Comment (shubham1172) [inline utils/utils.go:407]:
```suggestion
// SanitizeDir sanitizes the input string to make it a valid directory.
```

**Review by shubham1172 — APPROVED** [review]
